import { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { Layout, Post, RequiredLogin } from "~/components";
import { Comment } from "~/components/Comment";
import AddComment from "~/components/post-detail/AddComment";
import { api } from "~/utils/api";

const PostDetail: NextPage = () => {
  const { query } = useRouter();
  const { data: session } = useSession();
  const postId = query.slug as string;

  const { data, isLoading } = api.post.postDetail.useQuery(
    { postId },
    { enabled: postId !== undefined }
  );

  return (
    <>
      <Head>
        <title>Chuaks Post</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {isLoading && <div>Loading...</div>}
        {data && <Post post={data} />}
        {session ? (
          <AddComment postId={postId} />
        ) : (
          <RequiredLogin text="Please Sign In to comment in this post" />
        )}
        {data?.comments.map((comment) => (
          <Comment key={comment.id} comment={comment} />
        ))}
      </Layout>
    </>
  );
};

export default PostDetail;
