import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";

import { CreatePost, Layout, Post, RequiredLogin } from "~/components";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data, isLoading } = api.post.getAll.useQuery();
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Post It</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {session ? (
          <CreatePost />
        ) : (
          <RequiredLogin text="Please Sign In to interact with post(s)" />
        )}
        {isLoading && <div>Loading...</div>}
        {data?.map((post) => (
          <Post key={post.id} post={post} />
        ))}
      </Layout>
    </>
  );
};

export default Home;
