import { type NextPage } from "next";
import Head from "next/head";

import { CreatePost, Layout } from "~/components";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Post It</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <section>
          <h2>Post It!</h2>
          <CreatePost />
        </section>
      </Layout>
    </>
  );
};

export default Home;
